//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notification_id { get; set; }
        public string reminder_description { get; set; }
        public Nullable<System.DateTime> sending_date { get; set; }
        public Nullable<byte> sent { get; set; }
        public int notifcation_type_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual User User { get; set; }
        public virtual Notification_type Notification_type { get; set; }
    }
}
