//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GymData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int payment_id { get; set; }
        public int bill_id { get; set; }
        public Nullable<System.DateTime> date_payed { get; set; }
        public double amount { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
